version: "3.1"

services:
  delay_report:
    image: delay_report:latest
    build:
      context: .
      dockerfile: ./Dockerfile  
    command: poetry run python manage.py runserver 0.0.0.0:8000
    ports:
      - 127.0.0.1:8000:8000
    environment:
      - DJANGO_DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE=${DATABASE}
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - REDIS_URL=${REDIS_URL}  
    networks:
      - snappfood 
    depends_on:
      - postgres

  celery:
    image: delay_report_celery:latest
    build:
      context: .
      dockerfile: ./Dockerfile
    command: poetry run celery -A delay_report worker --loglevel=debug --concurrency=1
    environment:
      - DJANGO_DEBUG=${DEBUG}
      - SECRET_KEY=${SECRET_KEY}
      - DATABASE=${DATABASE}
      - DATABASE_ENGINE=${DATABASE_ENGINE}
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - CELERY_BROKER_URL=${CELERY_BROKER_URL}
      - REDIS_URL=${REDIS_URL}  
    networks:
      - snappfood
    depends_on:
      - postgres
      - redis

  postgres:
    image: postgres:16
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    ports:
      - 127.0.0.1:5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data/      
    networks:
      - snappfood

  redis:
    image: redis:7
    ports:
      - 127.0.0.1:6379:6379
    volumes:
      - redis_data:/data
    networks:
      - snappfood

  adminer:
    image: adminer:4
    ports:
      - 127.0.0.1:8080:8080
    networks:
      - snappfood  

volumes:
  postgres_data:
  redis_data:

networks:
  snappfood:
    driver: bridge
