# Generated by Django 4.2.9 on 2024-01-29 08:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.PositiveIntegerField(verbose_name='مدت زمان تحویل')),
                ('deliver_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان رسیدن سفارش')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='زمان سفارش')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
            ],
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='نام فروشنده')),
            ],
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('A', 'ASSIGNED'), ('V', 'AT VENDOR'), ('P', 'PICKED'), ('D', 'DELIVERED')], max_length=2, null=True, verbose_name='وضعیت')),
                ('created_time', models.DateTimeField(auto_now=True, verbose_name='زمان ایجاد')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trip', to='core.order', verbose_name='سفارش')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor', verbose_name='فروشنده'),
        ),
        migrations.CreateModel(
            name='DelayReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_time', models.PositiveIntegerField(verbose_name='مدت زمان تحویل')),
                ('deliver_at', models.DateTimeField(verbose_name='زمان رسیدن سفارش')),
                ('delay', models.PositiveIntegerField(null=True, verbose_name='زمان تاخیر')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='زمان گزارش')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='زمان ویرایش')),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='کارمند')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.order', verbose_name='سفارش')),
                ('vendor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor', verbose_name='فروشگاه')),
            ],
        ),
    ]
