# Generated by Django 4.2.9 on 2024-01-29 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delayreport',
            name='agent',
        ),
    ]
